# Module manifest for module 'EasyJobPS'
# Generated by: Akshin Mustafayev
# Generated on: 10/8/2021

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'EasyJobPS.psm1'
    
    # Version number of this module.
    ModuleVersion     = '1.0'
    
    # ID used to uniquely identify this module
    GUID              = 'd6c56376-ae08-4c23-b901-9bc75144e0c6'
    
    # Author of this module
    Author            = 'Akshin Mustafayev'
    
    # Company or vendor of this module
    CompanyName       = 'Akshin Mustafayev'
    
    # Copyright statement for this module
    Copyright         = '(c) 2021 Akshin Mustafayev. Apache-2.0 license.'
    
    # Description of the functionality provided by this module
    Description       = 'Module for implementing EasyJob additional helper functions'
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = 'Show-EJInputBox'
    
}